#! /bin/bash

# Default packages are for the configuration and corresponding .config folders
# Install packages after installing base Debian with no GUI

# xorg display server installation
sudo apt install -y xorg xbacklight xbindkeys xvkbd xinput

# PACKAGE INCLUDES build-essential.
sudo apt install -y build-essential

# Microcode for Intel/AMD 
# sudo apt install -y amd64-microcode
sudo apt install -y intel-microcode 

# Network File Tools/System Events
sudo apt install -y dialog mtools dosfstools avahi-daemon acpi acpid gvfs-backends

sudo systemctl enable avahi-daemon
sudo systemctl enable acpid

# File Manager (eg. pcmanfm,krusader,thunar)
sudo apt install -y thunar catfish

# Terminal (eg. terminator,kitty,xfce4-terminal)
sudo apt install -y terminator

# Sound packages
sudo apt install -y pulseaudio alsa-utils pavucontrol volumeicon-alsa

# Neofetch/HTOP
sudo apt install -y neofetch htop

# Network Manager
sudo apt install -y network-manager network-manager-gnome 

# Installation for Appearance management
sudo apt install -y lxappearance 

# Browser Installation (eg. chromium)
sudo apt install -y firefox-esr 

# Desktop background browser/handler 
# feh --bg-fill /path/to/directory 
# sudo apt install -y nitrogen 
sudo apt install -y nitrogen
 
# Fonts and icons for now
sudo apt install -y fonts-firacode fonts-liberation2 fonts-ubuntu fonts-cascadia-code

# Openbox packages
sudo apt install -y openbox dunst dbus-x11 hsetroot libnotify-bin menu picom qt5-style-plugins rofi tint2 xfce4-power-manager xfce4-keyboard-settings xfce4-mouse-settings xfce4-screenshooter

# Qt5 customisation
sudo apt install -y qt5ct qt5-gtk2-platformtheme

# LightDM login manager
sudo apt install -y lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
sudo systemctl enable lightdm

# Additional packages (if you fork this project, you might want to customise this part on your own)
sudo apt install libreoffice libreoffice-gtk3 gimp parole deadbeef galculator viewnior engrampa atril

sudo apt autoremove --purge
echo -e "Base installation ready. For config files, run the rice script."
